services:
  app:
    image: fiaposts
    ports:
      - "3010:3010"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fiaposts
      - JWT_SECRET=fiap@2024
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fiaposts
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
