services:
  fiaposts-api:
    image: fiaposts-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3010:3010"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fiaposts
      - JWT_SECRET=fiap@2024
    command: >
      bash -c "npm run prisma:migrate &&
               npm run prisma:seed &&
               npm run start"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fiaposts
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
